#!/usr/bin/env Rscript

files <- list.files(c("java","scala","sbt"),"[0-9]",recursive=TRUE,full.names=TRUE)
dirname <- "verify-tmp"
unlink(dirname,TRUE,TRUE)
dir.create(dirname,FALSE)
names <- file.path(dirname, sub("\\.-","",gsub("/","-",files)))
for ( i in seq_along(files) ) {
  cat("Working on",i,files[i],names[i],"")
  url <- readLines(files[i])
  cat(url,"\n")
  download.file(url,names[i])
}

system2("diff",file.path(dirname,c("sbt-1.2-1","sbt-1.2-2")),stdout=TRUE)
system2("diff",file.path(dirname,c("scala-2.11-1","scala-2.11-2")),stdout=TRUE)
system2("diff",file.path(dirname,c("scala-2.12-1","scala-2.12-2")),stdout=TRUE)
system2("diff",file.path(dirname,c("scala-2.13-1","scala-2.13-2")),stdout=TRUE)

