#!/bin/bash

if [[ -z "$VERSIONS" ]]
then
  >&2 echo "Oops, this script should be run via the ./run script."
  exit 1
fi

export SCALA_HOME=
PATH_WITHOUT_SCALA=/home/dahl/bin:/home/dahl/bin:/home/dahl/local/texlive/current/bin/x86_64-linux:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin

for SCALA_VERSION in $VERSIONS
do
  echo "Running battery for $SCALA_VERSION"

  # By setting the scala.home argument
  scala_home=~/local/scala/scala-$SCALA_VERSION
  R --slave -e 'library(rscala); print(scalaInfo("'$scala_home'",verbose=TRUE)$cmd)'

  # By setting the SCALA_HOME environment variable
  SCALA_HOME=$scala_home R --slave -e 'library(rscala); print(scalaInfo(verbose=TRUE)$cmd)'

  # By setting the PATH environment variable
  PATH=$PATH_WITHOUT_SCALA:/home/dahl/local/scala/scala-$SCALA_VERSION/bin /home/dahl/local/bin/R --slave -e 'library(rscala); print(scalaInfo(verbose=TRUE)$cmd)'

  echo "--------"
done

rm -rf ~/.rscala
PATH=$PATH_WITHOUT_SCALA /home/dahl/local/bin/R --slave -e 'library(rscala); scalaInstall(); print(scalaInfo(verbose=TRUE)$cmd)'

