PCODE_EXIT  <- 0L
PCODE_PUSH  <- 1L
PCODE_POP   <- 2L
BYTES_PER_INT <- 4L
BYTES_PER_DOUBLE <- 8L
TCODE_INT_0 <- 1000L
SSNIPPET_INT_0 <- "RScalaStack.pop().asInstanceOf[Int]"
TCODE_INT_1 <- 1001L
SSNIPPET_INT_1 <- "RScalaStack.pop().asInstanceOf[Array[Int]]"
TCODE_DOUBLE_0 <- 1010L
SSNIPPET_DOUBLE_0 <- "RScalaStack.pop().asInstanceOf[Double]"
TCODE_DOUBLE_1 <- 1011L
SSNIPPET_DOUBLE_1 <- "RScalaStack.pop().asInstanceOf[Array[Double]]"
TCODE_LOGICAL_0 <- 1020L
SSNIPPET_LOGICAL_0 <- "RScalaStack.pop().asInstanceOf[Boolean]"
TCODE_LOGICAL_1 <- 1021L
SSNIPPET_LOGICAL_1 <- "RScalaStack.pop().asInstanceOf[Array[Boolean]]"
TCODE_RAW_0 <- 1030L
SSNIPPET_RAW_0 <- "RScalaStack.pop().asInstanceOf[Byte]"
TCODE_RAW_1 <- 1031L
SSNIPPET_RAW_1 <- "RScalaStack.pop().asInstanceOf[Array[Byte]]"
TCODE_CHARACTER_0 <- 1040L
SSNIPPET_CHARACTER_0 <- "RScalaStack.pop().asInstanceOf[String]"
TCODE_CHARACTER_1 <- 1041L
SSNIPPET_CHARACTER_1 <- "RScalaStack.pop().asInstanceOf[Array[String]]"
