#!/bin/bash

exec scala -nc -cp ../R/rscala/inst/java/scala-2.12/rscala_2.12-3.2.0.jar
#scala -nc -cp ../R/rscala/inst/java/scala-2.12/rscala_2.12-3.2.0.jar

!#

// val R = org.ddahl.rscala.RClient("R",0,true)
val R = org.ddahl.rscala.RClient()

val a = R.evalD0("3+4")
R.eval("cat(3+4,'\n')")
R.quit()


R.eval("b <- %-",Array(1,2,3,4,5))
R.evalD1("b")

val a = R.evalObject("function(x) 2*x")
R.evalD0("%-(5)",a)

val a = R.evalObject("function(x) stop('b')")
R.eval("%-(5)",a)

R.eval("b <- %-",Array(1,2,3,4,5))
R.evalD0("b")

